language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install --no-interaction
  - composer require php-coveralls/php-coveralls
  - composer dump-autoload --optimize

script:
  - mkdir ./tests/logs/
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - travis_retry php vendor/bin/coveralls -v

matrix:
  fast_finish: true
