language: php

php:
  - 5.6
  - 7.0

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --no-interaction
  - php composer.phar require satooshi/php-coveralls
  - php composer.phar dump-autoload --optimize

script:
  - mkdir ./tests/logs/
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - travis_retry php vendor/bin/coveralls -v

matrix:
  fast_finish: true
  allow_failures:
    - php: "7.0"
