build: off
platform:
  - x86
  - x64
clone_folder: C:\projects\meteor
install:
  - appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-5.5.9-nts-Win32-VC11-x86.zip
  - 7z x php-5.5.9-nts-Win32-VC11-x86.zip -y >nul
  - del /Q *.zip
  - IF NOT EXIST composer.phar (appveyor DownloadFile https://getcomposer.org/download/1.2.0/composer.phar)
  - php composer.phar self-update
  - php composer.phar install --no-interaction
  - php composer.phar dump-autoload --optimize
